version: 0.2

phases:
    pre_build:
        commands: 
            - apt-get update
            - aws --version
            - echo logging in to Amazon
            - $(aws ecr get-login --region ap-south-1 --no-include-email)
            - REPOSITORY_URI=131872871854.dkr.ecr.ap-south-1.amazonaws.com/springbackend
      
    build:
        commands:
            - echo Build started on `date`
            - echo Building Docker image...
            - docker build -t springbackend .
            - docker tag springbackend:latest $REPOSITORY_URI:latest
            
    post_build:
        commands:
            - echo Build completed on `date`
            - echo Pushing the Docker images
            - docker push $REPOSITORY_URI:latest
artifacts:
    files:
        - '**/*'
    base_directory: 'SpringBackend'