version: 0.2

phases:
    pre_build:
        commands: 
            - apt-get update
            - echo logging in to Amazon
            - aws ecr-public get-login-password --region ap-south-1 | docker login --username AWS --password-stdin public.ecr.aws/e0l1n5a0
      
    build:
        commands:
            - echo Build started on `date`
            - echo Building Docker image...
            - docker build -t springbackend .
            - docker tag springbackend:latest public.ecr.aws/e0l1n5a0/springbackend:latest
            
    post_build:
        commands:
            - echo Build completed on `date`
            - echo Pushing the Docker images
            - docker push public.ecr.aws/e0l1n5a0/springbackend:latest
artifacts:
    files:
        - '**/*'
    base_directory: 'SpringBackend'