version: 0.2

phases:
    pre_build:
        commands: 
            - apt-get update
            - apt-get install -y jq
            - wget http://www-eu.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
            - tar xzf apache-maven-3.5.4-bin.tar.gz
            - ln -s apache-maven-3.5.4 maven
            - echo logging in to Amazon
            # docker login
      
    build:
        commands:
            - mvn clean install
            - rm -rf apache-maven-3.5.4-bin.tar.gz apache-maven-3.5.4
            - echo Build started on `date`
            - echo Building Docker image...
            - docker build -t deployment .
            - docker tag deployment:latest 131872871854.dkr.ecr.us-east-2.amazonaws.com/deployment:latest
            
    post_build:
        commands:
            - echo Build completed on `date`
            - echo Pushing the Docker images
            - docker push 131872871854.dkr.ecr.us-east-2.amazonaws.com/deployment:latest
artifacts:
    files:
        - '**/*'
    base_directory: 'SpringBackend'